# Generated by Django 5.2.17 on 2026-09-22 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0009_reserva_facturada_sin_excepciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('key_prefix', models.CharField(max_length=12, unique=True, verbose_name='prefijo de la clave')),
                ('key_hash', models.CharField(max_length=64, verbose_name='huella de la clave')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso')),
                ('user', models.OneToOneField(help_text='Sus oficinas son las que puede vender la web; su rol, lo que puede hacer.', on_delete=django.db.models.deletion.PROTECT, related_name='api_client', to=settings.AUTH_USER_MODEL, verbose_name='usuario tecnico')),
            ],
            options={
                'verbose_name': 'cliente de la API',
                'verbose_name_plural': 'clientes de la API',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('idempotency_key', models.CharField(max_length=80, verbose_name='clave de idempotencia')),
                ('request_hash', models.CharField(max_length=64, verbose_name='huella de la peticion')),
                ('external_ref', models.CharField(blank=True, max_length=80, verbose_name='referencia en la web')),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking_api.apiclient', verbose_name='cliente de la API')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='api_origin', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'reserva por API',
                'verbose_name_plural': 'reservas por API',
                'constraints': [models.UniqueConstraint(fields=('api_client', 'idempotency_key'), name='booking_api_idempotencia')],
            },
        ),
    ]
