# Generated by Django 5.2.17 on 2026-09-10 11:24

import apps.contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0008_cargos_de_devolucion'),
        ('settings_app', '0002_empresa_y_condiciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('status', models.CharField(choices=[('pending', 'Generandose'), ('ready', 'Listo'), ('failed', 'Fallo')], db_index=True, default='pending', max_length=20, verbose_name='estado')),
                ('file', models.FileField(blank=True, help_text='PDF firmado a mano en mostrador. Sin URL publica.', storage=apps.contracts.models.contrato_privado, upload_to='contratos/%Y/%m/', verbose_name='fichero')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='generado el')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_generated', to=settings.AUTH_USER_MODEL, verbose_name='generado por')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='reservations.reservation', verbose_name='reserva')),
                ('terms_version', models.ForeignKey(help_text='Que condiciones generales se imprimieron en este contrato.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='settings_app.termsversion', verbose_name='condiciones aplicadas')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['reservation', '-created_at'], name='contracts_reserva')],
            },
        ),
    ]
