# Generated by Django 5.2.17 on 2026-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'permisos de reservas',
                'permissions': [('change_reservation_price', 'Puede modificar el precio de una reserva a mano'), ('cancel_reservation', 'Puede cancelar una reserva'), ('delete_reservation', 'Puede eliminar una reserva')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
