# Generated by Django 5.2.17 on 2026-09-10 06:12

import apps.core.db
import apps.reservations.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehiculos_y_bloqueos'),
        ('offices', '0002_grupos_de_oficinas'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('code', models.CharField(help_text='Referencia con la que el cliente y el mostrador hablan de la reserva.', max_length=12, unique=True, verbose_name='localizador')),
                ('pickup_at', models.DateTimeField(verbose_name='recogida')),
                ('return_at', models.DateTimeField(verbose_name='devolucion')),
                ('rotation_minutes', models.PositiveSmallIntegerField(default=apps.reservations.models.default_rotation_minutes, help_text='Limpieza y revision despues de esta entrega. Se guarda en la reserva y no en la configuracion: cambiar el valor general no puede mover hacia atras la ocupacion de lo ya reservado.', verbose_name='minutos de rotacion')),
                ('occupancy_end', models.DateTimeField(editable=False, help_text='Devolucion mas la rotacion. Lo escribe save(), no se teclea.', verbose_name='fin de ocupacion')),
                ('occupancy_period', models.GeneratedField(db_persist=True, expression=apps.core.db.TsTzRange(models.F('pickup_at'), models.F('occupancy_end'), models.Value('[)')), output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), verbose_name='periodo de ocupacion')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada'), ('no_show', 'No show')], db_index=True, default='draft', max_length=20, verbose_name='estado')),
                ('needs_reassignment', models.BooleanField(db_index=True, default=False, help_text='El vehiculo que tenia asignado ya no esta en flota. La reserva sigue viva y hay que darle otro coche.', verbose_name='pendiente de reasignar')),
                ('overbooked', models.BooleanField(default=False, help_text='Se acepto por encima de la capacidad, con permiso y motivo.', verbose_name='forzada sin disponibilidad')),
                ('override_reason', models.TextField(blank=True, verbose_name='motivo del overbooking')),
                ('category', models.ForeignKey(help_text='Lo que se vende. El vehiculo concreto puede llegar despues.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='fleet.vehiclecategory', verbose_name='categoria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forced_reservations', to=settings.AUTH_USER_MODEL, verbose_name='forzada por')),
                ('pickup_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='offices.office', verbose_name='oficina de recogida')),
                ('return_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='offices.office', verbose_name='oficina de devolucion')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Opcional: una reserva puede existir contra la categoria.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-pickup_at'],
                'permissions': [('change_reservation_price', 'Puede modificar el precio de una reserva a mano'), ('cancel_reservation', 'Puede cancelar una reserva')],
            },
        ),
        migrations.DeleteModel(
            name='ReservationPermissions',
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['category', 'occupancy_period'], name='reservations_cat_periodo'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'pickup_at'], name='reservations_estado_recogida'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['pickup_office', 'pickup_at'], name='reservations_oficina_rec'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('return_at__gt', models.F('pickup_at'))), name='reservations_devolucion_posterior_a_recogida'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('occupancy_end__gte', models.F('return_at'))), name='reservations_ocupacion_cubre_el_alquiler'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('pending', 'confirmed', 'in_progress')), ('vehicle__isnull', False)), expressions=[('occupancy_period', '&&'), ('vehicle', '=')], name='reservations_vehiculo_sin_solapes', violation_error_message='Ese vehiculo ya esta comprometido en parte de ese periodo.'),
        ),
    ]
