# Generated by Django 5.2.17 on 2026-09-10 07:05

import apps.reservations.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('fleet', '0002_vehiculos_y_bloqueos'),
        ('offices', '0002_grupos_de_oficinas'),
        ('pricing', '0003_temporadas_tarifas_y_suplementos'),
        ('reservations', '0004_renombrar_code_a_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20, unique=True, verbose_name='ambito')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='ultimo numero')),
            ],
            options={
                'verbose_name': 'contador de reservas',
                'verbose_name_plural': 'contadores de reservas',
            },
        ),
        migrations.CreateModel(
            name='ReservationDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='apellidos')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('document_number', models.CharField(blank=True, max_length=20, verbose_name='numero de documento')),
                ('licence_number', models.CharField(max_length=30, verbose_name='numero de carnet')),
                ('licence_country', models.CharField(default='ES', max_length=2, verbose_name='pais del carnet')),
                ('licence_issued_on', models.DateField(blank=True, null=True, verbose_name='expedicion del carnet')),
                ('licence_expiry', models.DateField(blank=True, null=True, verbose_name='caducidad del carnet')),
            ],
            options={
                'verbose_name': 'conductor adicional',
                'verbose_name_plural': 'conductores adicionales',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(help_text='Nombre del extra cuando se vendio.', max_length=120, verbose_name='concepto')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio de una unidad por todo el alquiler, no por dia: es la linea tal como sale en el contrato y en la factura.', max_digits=10, verbose_name='precio unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tipo de impuesto')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
            ],
            options={
                'verbose_name': 'extra de la reserva',
                'verbose_name_plural': 'extras de la reserva',
                'ordering': ['concept'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada'), ('no_show', 'No show')], max_length=20, verbose_name='estado anterior')),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada'), ('no_show', 'No show')], max_length=20, verbose_name='estado nuevo')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cuando')),
            ],
            options={
                'verbose_name': 'cambio de estado',
                'verbose_name_plural': 'cambios de estado',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_pickup_at',
            field=models.DateTimeField(blank=True, help_text='La escribe el check-in. Sin ella la reserva no pasa a en curso.', null=True, verbose_name='recogida real'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_return_at',
            field=models.DateTimeField(blank=True, help_text='La escribe el check-out. Sin ella la reserva no se finaliza.', null=True, verbose_name='devolucion real'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='base del alquiler'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lo calcula la politica al cancelar. Se congela en ese momento.', max_digits=10, verbose_name='cargo por cancelacion'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Flexible: sin cargo hasta 24 h antes'), ('moderate', 'Moderada: sin cargo hasta 72 h antes'), ('strict', 'Estricta: se cobra el primer dia'), ('non_refundable', 'No reembolsable')], default='flexible', max_length=20, verbose_name='politica de cancelacion'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='channel',
            field=models.CharField(choices=[('counter', 'Mostrador'), ('web', 'Web'), ('partner', 'Partner')], db_index=True, default='counter', max_length=20, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Un borrador puede no tenerlo todavia; para confirmar es obligatorio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=apps.reservations.models.default_deposit, max_digits=10, verbose_name='fianza'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discounts_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total de descuentos (base)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total de extras (base)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='franchise_amount',
            field=models.DecimalField(decimal_places=2, default=apps.reservations.models.default_franchise, max_digits=10, verbose_name='franquicia'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fuel_policy',
            field=models.CharField(choices=[('full_full', 'Lleno - lleno'), ('full_empty', 'Lleno - vacio'), ('same_level', 'Mismo nivel')], default='full_full', max_length=20, verbose_name='politica de combustible'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='included_km',
            field=models.PositiveIntegerField(blank=True, help_text='En blanco: kilometraje ilimitado.', null=True, verbose_name='kilometros incluidos'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Solo para el mostrador. No se imprime.', verbose_name='notas internas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_price_manual',
            field=models.BooleanField(default=False, help_text='Se ha tocado el precio a mano. Exige permiso y motivo.', verbose_name='precio manual'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manual_price_reason',
            field=models.TextField(blank=True, default='', verbose_name='motivo del precio manual'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Lo que ve el cliente en el contrato.', verbose_name='notas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='El calculo entero tal como salio, linea a linea.', verbose_name='desglose'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rate',
            field=models.ForeignKey(blank=True, help_text='La que se aplico. Se conserva aunque despues se retire del catalogo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='pricing.rate', verbose_name='tarifa'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='supplements_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total de suplementos (base)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total de impuestos'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.CharField(editable=False, help_text='Serie correlativa sin huecos. Formato en RESERVATION_NUMBER_FORMAT.', max_length=30, unique=True, verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_at',
            field=models.DateTimeField(verbose_name='recogida prevista'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_at',
            field=models.DateTimeField(verbose_name='devolucion prevista'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer', '-pickup_at'], name='reservations_cliente'),
        ),
        migrations.AddField(
            model_name='reservationdriver',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Si ademas es cliente. No es obligatorio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driving_for', to='customers.customer', verbose_name='ficha de cliente'),
        ),
        migrations.AddField(
            model_name='reservationdriver',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='reservations.reservation', verbose_name='reserva'),
        ),
        migrations.AddField(
            model_name='reservationextra',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_lines', to='pricing.extra', verbose_name='extra'),
        ),
        migrations.AddField(
            model_name='reservationextra',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='reservations.reservation', verbose_name='reserva'),
        ),
        migrations.AddField(
            model_name='reservationstatuschange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='reservationstatuschange',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='reservations.reservation', verbose_name='reserva'),
        ),
        migrations.AddConstraint(
            model_name='reservationextra',
            constraint=models.UniqueConstraint(fields=('reservation', 'extra'), name='reservations_un_extra_una_vez_por_reserva'),
        ),
    ]
