# Generated by Django 5.2.17 on 2026-09-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reserva_completa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-pickup_at'], 'permissions': [('change_reservation_price', 'Puede modificar el precio de una reserva a mano'), ('cancel_reservation', 'Puede cancelar una reserva'), ('change_invoiced_reservation', 'Puede modificar una reserva que ya tiene factura emitida')], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
    ]
