# Generated by Django 5.2.17 on 2026-09-10 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_permiso_reserva_facturada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Precio puesto a mano'), ('recalculated', 'Recalculado desde tarifa'), ('dates', 'Cambio de fechas'), ('category', 'Cambio de categoria'), ('extras', 'Cambio de extras')], max_length=20, verbose_name='motivo del cambio')),
                ('previous_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total anterior')),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total nuevo')),
                ('reason', models.TextField(blank=True, default='', help_text='Obligatorio cuando el precio se pone a mano.', verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cuando')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_price_changes', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'cambio de precio',
                'verbose_name_plural': 'cambios de precio',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
