# Generated by Django 5.2.17 on 2026-09-10 11:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_registro_de_cambios_de_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='charges_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kilometros, combustible, retraso y danos. Con impuesto incluido.', max_digits=10, verbose_name='total de cargos'),
        ),
        migrations.CreateModel(
            name='ReservationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('extra_km', 'Kilometros de mas'), ('fuel', 'Combustible'), ('late_return', 'Devolucion tardia'), ('cleaning', 'Limpieza especial'), ('damage', 'Danos'), ('other', 'Otros')], max_length=20, verbose_name='tipo')),
                ('concept', models.CharField(max_length=160, verbose_name='concepto')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tipo de impuesto')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('is_automatic', models.BooleanField(default=True, help_text='Lo calculo la devolucion; si no, lo escribio una persona.', verbose_name='calculado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_charges', to=settings.AUTH_USER_MODEL, verbose_name='anadido por')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
