# Generated by Django 5.2.17 on 2026-09-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_cargos_de_devolucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-pickup_at'], 'permissions': [('change_reservation_price', 'Puede modificar el precio de una reserva a mano'), ('cancel_reservation', 'Puede cancelar una reserva')], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
    ]
