# Generated by Django 5.2.17 on 2026-09-09 20:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe un extra con ese codigo.'}, help_text='Identificador corto y estable. Aparece en factura y contrato.', max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('calculation_type', models.CharField(choices=[('once', 'Precio unico'), ('per_day', 'Por dia de alquiler'), ('per_reservation', 'Por reserva')], default='per_day', max_length=20, verbose_name='forma de cobro')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base imponible, sin impuesto.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='impuesto (%)')),
                ('max_quantity', models.PositiveSmallIntegerField(default=1, help_text='Cuantas unidades se pueden anadir a una misma reserva.', verbose_name='cantidad maxima')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Tope para los extras por dia. Vacio: sin tope.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='importe maximo')),
                ('requires_driver_data', models.BooleanField(default=False, help_text='Para el segundo conductor: obliga a rellenar sus datos y su carnet.', verbose_name='pide datos de conductor')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Menor primero. Fija el orden en el que se ofrecen.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'extra',
                'verbose_name_plural': 'extras',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
