# Generated by Django 5.2.17 on 2026-09-09 21:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehiculos_y_bloqueos'),
        ('offices', '0002_grupos_de_oficinas'),
        ('pricing', '0002_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe una temporada con ese codigo.'}, max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('start_date', models.DateField(verbose_name='desde')),
                ('end_date', models.DateField(verbose_name='hasta')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Mayor gana cuando dos temporadas cubren la misma fecha.', verbose_name='prioridad')),
            ],
            options={
                'verbose_name': 'temporada',
                'verbose_name_plural': 'temporadas',
                'ordering': ['-priority', 'start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='pricing_season_fechas')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='pricing_season_fin_posterior_al_inicio')],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe una tarifa con ese codigo.'}, max_length=30, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('channel', models.CharField(choices=[('counter', 'Mostrador'), ('web', 'Web'), ('partner', 'Partner')], db_index=True, default='counter', max_length=20, verbose_name='canal')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Mayor gana. A igual prioridad decide cual es mas especifica.', verbose_name='prioridad')),
                ('tier_mode', models.CharField(choices=[('flat', 'Plano'), ('progressive', 'Progresivo')], default='flat', help_text='Plano: todos los dias al precio del tramo que corresponde a la duracion. Progresivo: cada dia al precio de su propio tramo.', max_length=20, verbose_name='modo de tramos')),
                ('included_km_per_day', models.PositiveIntegerField(blank=True, help_text='Vacio: kilometraje ilimitado.', null=True, verbose_name='km incluidos por dia')),
                ('extra_km_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio del km de mas')),
                ('min_days', models.PositiveSmallIntegerField(default=1, verbose_name='dias minimos')),
                ('max_days', models.PositiveSmallIntegerField(blank=True, help_text='Vacio: sin limite.', null=True, verbose_name='dias maximos')),
                ('categories', models.ManyToManyField(help_text='Categorias a las que se aplica esta tarifa.', related_name='rates', to='fleet.vehiclecategory', verbose_name='categorias')),
                ('offices', models.ManyToManyField(blank=True, help_text='Vacio: se aplica en todas las oficinas.', related_name='rates', to='offices.office', verbose_name='oficinas')),
                ('season', models.ForeignKey(blank=True, help_text='Vacio: vale para cualquier fecha dentro de su vigencia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='pricing.season', verbose_name='temporada')),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifas',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe un suplemento con ese codigo.'}, max_length=30, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('supplement_type', models.CharField(choices=[('one_way', 'Devolucion en otra oficina'), ('young_driver', 'Conductor joven'), ('after_hours', 'Fuera de horario'), ('airport', 'Aeropuerto')], db_index=True, max_length=20, verbose_name='tipo')),
                ('amount_type', models.CharField(choices=[('fixed', 'Importe fijo'), ('percent', 'Porcentaje sobre la base del alquiler')], default='fixed', max_length=20, verbose_name='forma de calculo')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Euros si es fijo; porcentaje sobre la base si es porcentual.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='importe')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='impuesto (%)')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, help_text='Conductor joven: desde que edad se cobra (normalmente 18).', null=True, verbose_name='edad minima')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, help_text='Conductor joven: hasta que edad se cobra (normalmente 24).', null=True, verbose_name='edad maxima')),
                ('hours_from', models.TimeField(blank=True, help_text='Fuera de horario: apertura de la oficina.', null=True, verbose_name='horario desde')),
                ('hours_to', models.TimeField(blank=True, help_text='Fuera de horario: cierre de la oficina.', null=True, verbose_name='horario hasta')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='orden')),
                ('offices', models.ManyToManyField(blank=True, help_text='Aeropuerto: oficinas que lo cobran. Vacio: ninguna.', related_name='supplements', to='offices.office', verbose_name='oficinas')),
            ],
            options={
                'verbose_name': 'suplemento',
                'verbose_name_plural': 'suplementos',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(blank=True, help_text='Vacio: se aplica solo, sin que nadie lo teclee.', max_length=30, verbose_name='codigo promocional')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('amount_type', models.CharField(choices=[('fixed', 'Importe fijo'), ('percent', 'Porcentaje sobre la base del alquiler')], default='percent', max_length=20, verbose_name='forma de calculo')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Euros si es fijo; porcentaje sobre la base del alquiler si es porcentual.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='importe')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('min_days', models.PositiveSmallIntegerField(blank=True, help_text='Solo a partir de esta duracion.', null=True, verbose_name='dias minimos')),
                ('categories', models.ManyToManyField(blank=True, help_text='Vacio: cualquier categoria.', related_name='discounts', to='fleet.vehiclecategory', verbose_name='categorias')),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='pricing_discount_codigo_unico', violation_error_message='Ya existe un descuento con ese codigo.')],
            },
        ),
        migrations.CreateModel(
            name='RateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.PositiveSmallIntegerField(verbose_name='desde (dias)')),
                ('max_days', models.PositiveSmallIntegerField(blank=True, help_text='Vacio: sin limite (el ultimo tramo).', null=True, verbose_name='hasta (dias)')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio por dia')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing.rate', verbose_name='tarifa')),
            ],
            options={
                'verbose_name': 'tramo de tarifa',
                'verbose_name_plural': 'tramos de tarifa',
                'ordering': ['rate', 'min_days'],
                'constraints': [models.UniqueConstraint(fields=('rate', 'min_days'), name='pricing_tier_inicio_unico', violation_error_message='Esa tarifa ya tiene un tramo que empieza ese dia.'), models.CheckConstraint(condition=models.Q(('max_days__isnull', True), ('max_days__gte', models.F('min_days')), _connector='OR'), name='pricing_tier_dias_coherentes')],
            },
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='pricing_rate_vigencia_coherente'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(condition=models.Q(('max_days__isnull', True), ('max_days__gte', models.F('min_days')), _connector='OR'), name='pricing_rate_dias_coherentes'),
        ),
    ]
