# Generated by Django 5.2.17 on 2026-09-09 20:44

import apps.customers.models
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # El indice trigram del buscador necesita la extension pg_trgm.
        ('core', '0002_pg_trgm'),
        ('offices', '0002_grupos_de_oficinas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='apellidos')),
                ('birth_date', models.DateField(blank=True, help_text='Necesaria para el suplemento de conductor joven.', null=True, verbose_name='fecha de nacimiento')),
                ('nationality', models.CharField(default='ES', max_length=2, verbose_name='nacionalidad')),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('nie', 'NIE'), ('passport', 'Pasaporte')], default='dni', max_length=20, verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='numero de documento')),
                ('document_expiry', models.DateField(blank=True, null=True, verbose_name='caducidad del documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefono')),
                ('phone_alt', models.CharField(blank=True, max_length=20, verbose_name='telefono alternativo')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='direccion')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='localidad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='codigo postal')),
                ('country', models.CharField(default='ES', max_length=2, verbose_name='pais')),
                ('licence_number', models.CharField(blank=True, max_length=30, verbose_name='numero de carnet')),
                ('licence_country', models.CharField(default='ES', max_length=2, verbose_name='pais del carnet')),
                ('licence_issued_on', models.DateField(blank=True, help_text='De aqui sale la antiguedad de carnet que exigen las tarifas.', null=True, verbose_name='fecha de expedicion')),
                ('licence_expiry', models.DateField(blank=True, null=True, verbose_name='caducidad del carnet')),
                ('notes', models.TextField(blank=True, help_text='No se imprimen en el contrato ni las ve el cliente.', verbose_name='notas internas')),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False, help_text='Se avisa al crear una reserva con este cliente.', verbose_name='cliente conflictivo')),
                ('blacklist_reason', models.TextField(blank=True, help_text='Que paso. Lo lee quien esta en el mostrador antes de alquilar.', verbose_name='motivo')),
                ('search_text', models.TextField(blank=True, editable=False, verbose_name='texto de busqueda')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('office', models.ForeignKey(blank=True, help_text='Donde se dio de alta. No limita quien puede atenderle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='offices.office', verbose_name='oficina de alta')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('kind', models.CharField(choices=[('id_front', 'Documento de identidad (anverso)'), ('id_back', 'Documento de identidad (reverso)'), ('licence_front', 'Carnet de conducir (anverso)'), ('licence_back', 'Carnet de conducir (reverso)'), ('other', 'Otro')], default='id_front', max_length=20, verbose_name='tipo')),
                ('file', models.FileField(storage=apps.customers.models.documentos_privados, upload_to=apps.customers.models.ruta_documento, verbose_name='fichero')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='nombre original')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='descripcion')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer', verbose_name='cliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'documento de cliente',
                'verbose_name_plural': 'documentos de cliente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='customers_busqueda_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_nombre'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('document_type', 'document_number'), name='customers_documento_unico', violation_error_message='Ya hay un cliente con ese documento.'),
        ),
    ]
