# Generated by Django 5.2.17 on 2026-09-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_support',
            field=models.CharField(blank=True, help_text='El que aparece en el DNI o NIE (IDESP / soporte). Lo exige SES.Hospedajes.', max_length=20, verbose_name='numero de soporte'),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('de', 'Alemán'), ('fr', 'Francés')], default='es', help_text='Idioma de los correos, la factura y el contrato que recibe.', max_length=5, verbose_name='idioma'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Hombre'), ('female', 'Mujer'), ('other', 'Otro')], help_text='Lo exige el parte de SES.Hospedajes.', max_length=10, verbose_name='sexo'),
        ),
    ]
