# Generated by Django 5.2.17 on 2026-09-09 14:01

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('is_system', models.BooleanField(default=False, help_text='Definido en codigo. sync_roles lo mantiene al dia.', verbose_name='del sistema')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='apellidos')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefono')),
                ('is_active', models.BooleanField(default=True, help_text='Un usuario desactivado no puede entrar. Nunca se borra.', verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Da acceso al admin interno de Django. No es el panel de gestion.', verbose_name='soporte tecnico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('offices', models.ManyToManyField(blank=True, help_text='Oficinas sobre las que puede operar. Sin oficinas no ve datos.', related_name='users', to='offices.office', verbose_name='oficinas')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='rol')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['last_name', 'first_name', 'email'],
                'permissions': [('manage_users', 'Puede gestionar usuarios, roles y oficinas asignadas')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
