# Generated by Django 5.2.17 on 2026-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'permisos de facturacion',
                'permissions': [('view_billing', 'Puede consultar facturacion y cobros'), ('add_payment', 'Puede registrar cobros')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
