# Generated by Django 5.2.17 on 2026-09-10 07:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('offices', '0002_grupos_de_oficinas'),
        ('reservations', '0007_registro_de_cambios_de_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_billing', 'Puede consultar facturacion y cobros')], 'verbose_name': 'permisos de facturacion'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negativo en devoluciones y reembolsos.', max_digits=10, verbose_name='importe')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('paypal', 'PayPal'), ('dataphone', 'Datafono'), ('other', 'Otros')], max_length=20, verbose_name='medio de pago')),
                ('payment_type', models.CharField(choices=[('advance', 'Anticipo'), ('payment', 'Pago'), ('deposit', 'Fianza'), ('deposit_return', 'Devolucion de fianza'), ('additional_charge', 'Cargo adicional'), ('refund', 'Reembolso')], default='payment', max_length=20, verbose_name='concepto')),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha del cobro')),
                ('reference', models.CharField(blank=True, default='', help_text='Numero de operacion del datafono, del banco o del recibo.', max_length=60, verbose_name='referencia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('office', models.ForeignKey(help_text='Donde se cobro. Es la oficina que cuadra caja.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='offices.office', verbose_name='oficina')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
                'ordering': ['-paid_at', '-id'],
                'permissions': [('allow_overpayment', 'Puede cobrar por encima del pendiente')],
                'indexes': [models.Index(fields=['office', 'paid_at'], name='billing_pago_oficina_fecha'), models.Index(fields=['reservation', 'paid_at'], name='billing_pago_reserva')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='billing_importe_distinto_de_cero'), models.CheckConstraint(condition=models.Q(models.Q(('amount__lt', 0), ('payment_type__in', ('refund', 'deposit_return'))), models.Q(('amount__gt', 0), ('payment_type__in', ('advance', 'payment', 'deposit', 'additional_charge'))), _connector='OR'), name='billing_signo_coherente_con_el_concepto')],
            },
        ),
    ]
