# Generated by Django 5.2.17 on 2026-09-21 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def crear_series_por_defecto(apps, schema_editor):
    """Una serie de ordinarias y otra de rectificativas, para poder facturar ya.

    Solo si no hay ninguna: quien ya tenga sus series no las ve cambiar.
    """
    InvoiceSeries = apps.get_model("billing", "InvoiceSeries")
    if InvoiceSeries.objects.exists():
        return
    InvoiceSeries.objects.create(
        code="f",
        name="Facturas",
        kind="ordinary",
        number_format="F{year}-{sequence:05d}",
        is_default=True,
    )
    InvoiceSeries.objects.create(
        code="fr",
        name="Rectificativas",
        kind="rectifying",
        number_format="FR{year}-{sequence:05d}",
        is_default=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_permiso_add_payment_al_modelo'),
        ('offices', '0002_grupos_de_oficinas'),
        ('reservations', '0008_cargos_de_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe una serie con ese codigo.'}, max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('ordinary', 'Ordinaria'), ('rectifying', 'Rectificativa')], default='ordinary', max_length=20, verbose_name='tipo')),
                ('number_format', models.CharField(default='F{year}-{sequence:05d}', help_text='Usa {sequence} para el correlativo y, si quieres que se reinicie cada ano, {year}. Ejemplo: F{year}-{sequence:05d} da F2026-00001.', max_length=40, verbose_name='formato del numero')),
                ('is_default', models.BooleanField(default=False, help_text='La que se propone al emitir. Solo una por tipo.', verbose_name='serie por defecto')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas')),
            ],
            options={
                'verbose_name': 'serie de facturacion',
                'verbose_name_plural': 'series de facturacion',
                'ordering': ['kind', 'code'],
                'default_permissions': ('view', 'add', 'change'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('kind',), name='billing_una_serie_por_defecto_por_tipo')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('scope', models.CharField(max_length=20, verbose_name='ambito de numeracion')),
                ('sequence', models.PositiveIntegerField(verbose_name='correlativo')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='numero')),
                ('kind', models.CharField(choices=[('ordinary', 'Ordinaria'), ('rectifying', 'Rectificativa')], max_length=20, verbose_name='tipo')),
                ('issued_at', models.DateTimeField(db_index=True, verbose_name='fecha de expedicion')),
                ('rectification_reason', models.TextField(blank=True, default='', verbose_name='motivo de la rectificacion')),
                ('issuer_name', models.CharField(max_length=160, verbose_name='emisor')),
                ('issuer_tax_id', models.CharField(max_length=12, verbose_name='NIF del emisor')),
                ('issuer_address', models.CharField(max_length=300, verbose_name='direccion del emisor')),
                ('customer_name', models.CharField(max_length=200, verbose_name='cliente')),
                ('customer_tax_id', models.CharField(max_length=20, verbose_name='NIF del cliente')),
                ('customer_address', models.CharField(blank=True, default='', max_length=300, verbose_name='direccion del cliente')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='impuestos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='moneda')),
                ('hash_anterior', models.CharField(blank=True, default='', max_length=64, verbose_name='huella anterior')),
                ('hash_actual', models.CharField(max_length=64, unique=True, verbose_name='huella')),
                ('qr_data', models.CharField(max_length=400, verbose_name='contenido del QR')),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha del registro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to=settings.AUTH_USER_MODEL, verbose_name='emitida por')),
                ('office', models.ForeignKey(help_text='La de la reserva. Decide quien puede ver la factura.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='offices.office', verbose_name='oficina')),
                ('rectifies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to='billing.invoice', verbose_name='rectifica a')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reservations.reservation', verbose_name='reserva')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.invoiceseries', verbose_name='serie')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['-issued_at', '-id'],
                'permissions': [('rectify_invoice', 'Puede emitir facturas rectificativas')],
                'default_permissions': ('add',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceSeriesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20, verbose_name='ambito')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='ultimo numero')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='billing.invoiceseries', verbose_name='serie')),
            ],
            options={
                'verbose_name': 'contador de serie',
                'verbose_name_plural': 'contadores de serie',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('concept', models.CharField(max_length=200, verbose_name='concepto')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tipo de impuesto')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='billing.invoice', verbose_name='factura')),
            ],
            options={
                'verbose_name': 'linea de factura',
                'verbose_name_plural': 'lineas de factura',
                'ordering': ['invoice', 'position'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('invoice', 'position'), name='billing_linea_orden_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['office', 'issued_at'], name='billing_factura_oficina_fecha'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('series', 'scope', 'sequence'), name='billing_factura_correlativo_unico'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ordinary'), ('rectifies__isnull', True)), models.Q(('kind', 'rectifying'), ('rectifies__isnull', False)), _connector='OR'), name='billing_rectificativa_apunta_a_su_original'),
        ),
        migrations.AddConstraint(
            model_name='invoiceseriescounter',
            constraint=models.UniqueConstraint(fields=('series', 'scope'), name='billing_un_contador_por_serie_y_ambito'),
        ),
        migrations.RunPython(crear_series_por_defecto, migrations.RunPython.noop),
    ]
