# Generated by Django 5.2.17 on 2026-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_facturas_series_y_verifactu'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='policies',
            field=models.JSONField(blank=True, default=list, verbose_name='politicas impresas'),
        ),
    ]
