# Generated by Django 5.2.17 on 2026-09-21 09:29

import django.db.models.deletion
from django.db import migrations, models


def cliente_desde_la_reserva(apps, schema_editor):
    """Las facturas ya emitidas eran todas de una reserva: su cliente es el de ella.

    No cambia nada de lo facturado (los datos fiscales ya estaban copiados); solo
    deja explicito a quien se facturo.
    """
    from django.db.models import OuterRef, Subquery

    Invoice = apps.get_model("billing", "Invoice")
    Reservation = apps.get_model("reservations", "Reservation")
    Invoice.objects.filter(customer__isnull=True, reservation__isnull=False).update(
        customer=Subquery(
            Reservation.objects.filter(pk=OuterRef("reservation_id")).values("customer_id")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_politicas_impresas_en_factura'),
        ('customers', '0001_initial'),
        ('offices', '0002_grupos_de_oficinas'),
        ('reservations', '0008_cargos_de_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='A quien se factura. Sus datos fiscales van copiados aparte.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Salen impresas en la factura.', verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='office',
            field=models.ForeignKey(help_text='La de la reserva o la elegida. Decide quien puede ver la factura.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='offices.office', verbose_name='oficina'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Vacia en una factura libre: una multa, un cargo suelto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reservations.reservation', verbose_name='reserva'),
        ),
        migrations.RunPython(cliente_desde_la_reserva, migrations.RunPython.noop),
    ]
