# Generated by Django 5.2.17 on 2026-09-21 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_facturas_libres_a_cliente'),
        ('reservations', '0008_cargos_de_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token')),
                ('provider', models.CharField(max_length=20, verbose_name='pasarela')),
                ('purpose', models.CharField(choices=[('advance', 'Anticipo'), ('payment', 'Pago'), ('deposit', 'Fianza (preautorización)')], max_length=20, verbose_name='concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importe')),
                ('status', models.CharField(choices=[('created', 'Enlace creado'), ('pending', 'En la pasarela'), ('paid', 'Pagado'), ('authorized', 'Fianza retenida'), ('captured', 'Fianza cobrada'), ('released', 'Fianza liberada'), ('failed', 'Rechazado'), ('cancelled', 'Anulado'), ('expired', 'Caducado')], default='created', max_length=20, verbose_name='estado')),
                ('expires_at', models.DateTimeField(verbose_name='caduca')),
                ('provider_ref', models.CharField(blank=True, max_length=120, verbose_name='referencia en la pasarela')),
                ('provider_intent', models.CharField(blank=True, max_length=120, verbose_name='operacion')),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cobrado de la fianza')),
                ('last_event', models.JSONField(blank=True, default=dict, verbose_name='ultima notificacion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_payments_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='billing.payment', verbose_name='cobro')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'pago online',
                'verbose_name_plural': 'pagos online',
                'ordering': ['-created_at'],
                'default_permissions': ('view', 'add', 'change'),
            },
        ),
    ]
