# Generated by Django 5.2.17 on 2026-09-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('fleet', '0002_vehiculos_y_bloqueos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=40, verbose_name='ambito')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='fleet.vehiclecategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'cerrojo de categoria',
                'verbose_name_plural': 'cerrojos de categoria',
                'constraints': [models.UniqueConstraint(fields=('category', 'scope_key'), name='availability_cerrojo_unico_por_ambito')],
            },
        ),
    ]
