# Generated by Django 5.2.17 on 2026-09-09 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(help_text='Identificador corto y estable. Aparece en series de facturacion.', max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='direccion')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='localidad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('postal_code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='El codigo postal espanol tiene cinco digitos.', regex='^\\d{5}$')], verbose_name='codigo postal')),
                ('country', models.CharField(default='ES', max_length=2, verbose_name='pais')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
            ],
            options={
                'verbose_name': 'oficina',
                'verbose_name_plural': 'oficinas',
                'ordering': ['name'],
            },
        ),
    ]
