# Generated by Django 5.2.17 on 2026-09-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe un grupo con ese codigo.'}, help_text='Identificador corto y estable.', max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'grupo de oficinas',
                'verbose_name_plural': 'grupos de oficinas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='office',
            name='code',
            field=models.SlugField(error_messages={'unique': 'Ya existe una oficina con ese codigo.'}, help_text='Identificador corto y estable. Aparece en series de facturacion.', max_length=20, unique=True, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='office',
            name='pool',
            field=models.ForeignKey(blank=True, help_text='Oficinas entre las que la flota se mueve sin restricciones.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='offices.officepool', verbose_name='grupo de oficinas'),
        ),
    ]
