# Generated by Django 5.2.17 on 2026-09-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cuando')),
                ('action', models.CharField(choices=[('create', 'Alta'), ('update', 'Modificación'), ('status', 'Cambio de estado'), ('cancel', 'Cancelación'), ('price', 'Cambio de precio'), ('vehicle', 'Asignación de vehículo'), ('payment', 'Cobro'), ('invoice', 'Factura'), ('check_in', 'Entrega'), ('check_out', 'Devolución'), ('login', 'Acceso'), ('login_failed', 'Acceso fallido'), ('compliance', 'SES.Hospedajes'), ('email', 'Correo'), ('online_payment', 'Pago online'), ('maintenance', 'Mantenimiento'), ('fine', 'Multa')], max_length=20, verbose_name='accion')),
                ('message', models.CharField(max_length=255, verbose_name='que paso')),
                ('actor_repr', models.CharField(blank=True, max_length=160, verbose_name='usuario (copia)')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='id del objeto')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='objeto')),
                ('reservation_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='reserva')),
                ('office_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='oficina')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='cambios')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='navegador')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'apunte de auditoria',
                'verbose_name_plural': 'auditoria',
                'ordering': ['-created_at', '-id'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='auditlog_objeto'), models.Index(fields=['action', 'created_at'], name='auditlog_accion_fecha')],
            },
        ),
    ]
