# Generated by Django 5.2.17 on 2026-09-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('company', models.CharField(blank=True, default='', max_length=160, verbose_name='empresa')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo')),
                ('fleet_size', models.PositiveSmallIntegerField(blank=True, help_text='Tamano aproximado de la flota.', null=True, verbose_name='vehiculos')),
                ('message', models.TextField(blank=True, default='', verbose_name='mensaje')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('won', 'Cliente'), ('discarded', 'Descartado')], default='new', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas internas')),
            ],
            options={
                'verbose_name': 'contacto de la web',
                'verbose_name_plural': 'contactos de la web',
                'ordering': ['-created_at'],
            },
        ),
    ]
