# Generated by Django 5.2.17 on 2026-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'permisos de configuracion',
                'permissions': [('access_settings', 'Puede acceder a la configuracion de la empresa')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
