# Generated by Django 5.2.17 on 2026-09-10 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('legal_name', models.CharField(max_length=160, verbose_name='razon social')),
                ('trade_name', models.CharField(blank=True, default='', max_length=160, verbose_name='nombre comercial')),
                ('tax_id', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El CIF o NIF son entre 8 y 12 letras o numeros, sin espacios ni guiones.', regex='^[A-Za-z0-9]{8,12}$')], verbose_name='CIF / NIF')),
                ('address', models.CharField(max_length=200, verbose_name='direccion')),
                ('city', models.CharField(max_length=100, verbose_name='localidad')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='provincia')),
                ('postal_code', models.CharField(max_length=10, verbose_name='codigo postal')),
                ('country', models.CharField(default='ES', max_length=2, verbose_name='pais')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electronico')),
                ('website', models.URLField(blank=True, default='', verbose_name='web')),
                ('logo', models.ImageField(blank=True, help_text='Sale en la cabecera del contrato y de la factura.', upload_to='empresa/', verbose_name='logotipo')),
                ('registry_note', models.TextField(blank=True, default='', help_text='Inscripcion en el registro mercantil, si procede. Va en el pie.', verbose_name='nota registral')),
            ],
            options={
                'verbose_name': 'datos de la empresa',
                'verbose_name_plural': 'datos de la empresa',
            },
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('version', models.PositiveIntegerField(editable=False, unique=True, verbose_name='version')),
                ('title', models.CharField(default='Condiciones generales', max_length=160, verbose_name='titulo')),
                ('body', models.TextField(help_text='Una clausula por parrafo. Se imprime tal cual al final del contrato.', verbose_name='texto')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicada el')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='La que se aplica a los contratos nuevos. Solo puede haber una.', verbose_name='vigente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms_versions', to=settings.AUTH_USER_MODEL, verbose_name='redactada por')),
            ],
            options={
                'verbose_name': 'version de las condiciones',
                'verbose_name_plural': 'versiones de las condiciones',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='settings_una_sola_version_vigente')],
            },
        ),
    ]
