# Generated by Django 5.2.17 on 2026-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_empresa_y_condiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('body', models.TextField(verbose_name='texto')),
                ('show_on_invoice', models.BooleanField(default=True, help_text='Se imprime al pie de las facturas que se emitan a partir de ahora.', verbose_name='sale en las facturas')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Las de numero mas bajo salen primero.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'politica',
                'verbose_name_plural': 'politicas',
                'ordering': ['sort_order', 'title'],
                'default_permissions': ('view', 'add', 'change'),
            },
        ),
    ]
