# Generated by Django 5.2.17 on 2026-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_politicas_de_la_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='email_confirmation',
            field=models.BooleanField(default=True, verbose_name='correo de confirmacion'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_contract',
            field=models.BooleanField(default=True, verbose_name='enviar el contrato'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_invoice',
            field=models.BooleanField(default=True, verbose_name='enviar la factura'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_reminder',
            field=models.BooleanField(default=True, verbose_name='recordatorio antes de la recogida'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_return',
            field=models.BooleanField(default=True, verbose_name='correo tras la devolucion'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pickup_instructions',
            field=models.TextField(blank=True, default='', help_text='Salen en el recordatorio: donde esta el mostrador, que traer, como llegar. Se envian tal cual, en el idioma en que las escribas.', verbose_name='instrucciones de recogida'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='reminder_hours',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='horas de antelacion del recordatorio'),
        ),
    ]
