# Generated by Django 5.2.17 on 2026-09-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0008_cargos_de_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('status', models.CharField(choices=[('incomplete', 'Faltan datos'), ('ready', 'Lista para enviar'), ('sent', 'Enviada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('error', 'Error de envío')], default='incomplete', max_length=20, verbose_name='estado')),
                ('payload', models.JSONField(default=dict, verbose_name='datos')),
                ('xml', models.TextField(blank=True, verbose_name='XML')),
                ('missing', models.JSONField(blank=True, default=list, verbose_name='datos que faltan')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='plazo')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo intento')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada el')),
                ('simulated', models.BooleanField(default=False, help_text='Validada y guardada sin enviar: el envio real esta desactivado.', verbose_name='simulada')),
                ('lot_code', models.CharField(blank=True, max_length=60, verbose_name='codigo de lote')),
                ('response', models.TextField(blank=True, verbose_name='respuesta del Ministerio')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ses_submission', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'comunicacion a SES.Hospedajes',
                'verbose_name_plural': 'comunicaciones a SES.Hospedajes',
                'ordering': ['deadline_at', '-created_at'],
                'default_permissions': ('view', 'change'),
            },
        ),
    ]
