# Generated by Django 5.2.17 on 2026-09-10 11:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_cargos_de_devolucion'),
        ('offices', '0002_grupos_de_oficinas'),
        ('reservations', '0008_cargos_de_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('actual_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora de entrega')),
                ('mileage', models.PositiveIntegerField(verbose_name='kilometros')),
                ('fuel_level', models.PositiveSmallIntegerField(choices=[(0, 'Vacio'), (12, '1/8'), (25, '1/4'), (38, '3/8'), (50, '1/2'), (62, '5/8'), (75, '3/4'), (88, '7/8'), (100, 'Lleno')], default=100, help_text='Nivel del deposito al entregar, en octavos.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='combustible')),
                ('observations', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('licence_verified', models.BooleanField(default=False, verbose_name='carnet comprobado')),
                ('id_verified', models.BooleanField(default=False, verbose_name='DNI o pasaporte comprobado')),
                ('customer_signature', models.TextField(blank=True, default='', verbose_name='firma del cliente')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='firmado el')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='check_in', to='reservations.reservation', verbose_name='reserva')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-actual_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('actual_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora de devolucion')),
                ('mileage', models.PositiveIntegerField(verbose_name='kilometros')),
                ('fuel_level', models.PositiveSmallIntegerField(choices=[(0, 'Vacio'), (12, '1/8'), (25, '1/4'), (38, '3/8'), (50, '1/2'), (62, '5/8'), (75, '3/4'), (88, '7/8'), (100, 'Lleno')], default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='combustible')),
                ('observations', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_outs', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='check_out', to='reservations.reservation', verbose_name='reserva')),
                ('return_office', models.ForeignKey(help_text='Donde se devuelve de verdad. Puede no ser la prevista.', on_delete=django.db.models.deletion.PROTECT, related_name='check_outs', to='offices.office', verbose_name='oficina de devolucion')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_outs', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'devolucion',
                'verbose_name_plural': 'devoluciones',
                'ordering': ['-actual_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('zone', models.CharField(choices=[('front_bumper', 'Paragolpes delantero'), ('bonnet', 'Capo'), ('windscreen', 'Parabrisas'), ('roof', 'Techo'), ('front_left', 'Lateral delantero izquierdo'), ('rear_left', 'Lateral trasero izquierdo'), ('front_right', 'Lateral delantero derecho'), ('rear_right', 'Lateral trasero derecho'), ('rear_bumper', 'Paragolpes trasero'), ('boot', 'Porton trasero'), ('wheels', 'Ruedas y llantas'), ('interior', 'Interior')], max_length=20, verbose_name='zona')),
                ('damage_type', models.CharField(choices=[('scratch', 'Aranazo'), ('dent', 'Golpe o bollo'), ('broken', 'Rotura'), ('missing', 'Falta una pieza'), ('stain', 'Mancha'), ('other', 'Otros')], max_length=20, verbose_name='tipo')),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], default=1, verbose_name='gravedad')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripcion')),
                ('is_preexisting', models.BooleanField(db_index=True, default=False, help_text='Ya estaba cuando se entrego el coche. No se le cobra al cliente.', verbose_name='preexistente')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='coste estimado')),
                ('charge_to_customer', models.BooleanField(default=False, help_text='Un dano preexistente no se repercute nunca.', verbose_name='se repercute al cliente')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damages_recorded', to=settings.AUTH_USER_MODEL, verbose_name='anotado por')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='reservations.reservation', verbose_name='reserva')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'dano',
                'verbose_name_plural': 'danos',
                'ordering': ['zone', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('image', models.ImageField(upload_to='danos/%Y/%m/', verbose_name='foto')),
                ('caption', models.CharField(blank=True, default='', max_length=160, verbose_name='pie de foto')),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='operations.damage', verbose_name='dano')),
            ],
            options={
                'verbose_name': 'foto del dano',
                'verbose_name_plural': 'fotos del dano',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='damage',
            index=models.Index(fields=['vehicle', 'is_preexisting'], name='operations_dano_vehiculo'),
        ),
    ]
