# Generated by Django 5.2.17 on 2026-09-10 11:26

import apps.operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_entregas_devoluciones_y_danos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagephoto',
            name='image',
            field=models.ImageField(storage=apps.operations.models.foto_privada, upload_to='danos/%Y/%m/', verbose_name='foto'),
        ),
    ]
