# Generated by Django 5.2.17 on 2026-09-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_facturas_libres_a_cliente'),
        ('customers', '0001_initial'),
        ('fleet', '0003_cargos_de_devolucion'),
        ('offices', '0002_grupos_de_oficinas'),
        ('operations', '0002_fotos_privadas'),
        ('reservations', '0008_cargos_de_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('offense_at', models.DateTimeField(verbose_name='fecha y hora de la infraccion')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='lugar')),
                ('authority', models.CharField(help_text='DGT, ayuntamiento, Servei Catala de Transit...', max_length=120, verbose_name='organismo')),
                ('file_number', models.CharField(max_length=60, verbose_name='expediente')),
                ('description', models.TextField(blank=True, verbose_name='infraccion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importe')),
                ('notified_on', models.DateField(blank=True, null=True, verbose_name='fecha de notificacion')),
                ('identify_by', models.DateField(blank=True, help_text='Si se deja vacio: 20 dias naturales desde la notificacion.', null=True, verbose_name='plazo para identificar al conductor')),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('matched', 'Reserva localizada'), ('no_match', 'Sin reserva'), ('identified', 'Conductor identificado'), ('charged', 'Facturada al cliente'), ('closed', 'Cerrada')], default='received', max_length=20, verbose_name='estado')),
                ('driver_name', models.CharField(blank=True, max_length=200, verbose_name='conductor')),
                ('driver_document', models.CharField(blank=True, max_length=20, verbose_name='documento del conductor')),
                ('driver_licence', models.CharField(blank=True, max_length=30, verbose_name='carnet del conductor')),
                ('driver_address', models.CharField(blank=True, max_length=300, verbose_name='direccion del conductor')),
                ('identified_on', models.DateField(blank=True, null=True, verbose_name='identificado el')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='customers.customer', verbose_name='cliente responsable')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='billing.invoice', verbose_name='factura al cliente')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='offices.office', verbose_name='oficina')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='reservations.reservation', verbose_name='reserva')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'multa',
                'verbose_name_plural': 'multas',
                'ordering': ['-offense_at', '-id'],
                'default_permissions': ('view', 'add', 'change'),
                'constraints': [models.UniqueConstraint(fields=('authority', 'file_number'), name='operations_multa_expediente_unico')],
            },
        ),
    ]
