# Generated by Django 5.2.17 on 2026-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'permisos de informes',
                'permissions': [('view_reports', 'Puede consultar los informes y exportar para la gestoria')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
