# Generated by Django 5.2.17 on 2026-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('code', models.SlugField(error_messages={'unique': 'Ya existe una categoria con ese codigo.'}, help_text='Identificador corto y estable. Aparece en tarifas y contratos.', max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('image', models.ImageField(blank=True, help_text='Foto de referencia del grupo. No es un vehiculo concreto.', upload_to='categorias/', verbose_name='imagen')),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name='plazas')),
                ('doors', models.PositiveSmallIntegerField(default=5, verbose_name='puertas')),
                ('luggage', models.PositiveSmallIntegerField(default=2, help_text='Maletas grandes que caben en el maletero.', verbose_name='maletas')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatico')], default='manual', max_length=20, verbose_name='cambio')),
                ('fuel', models.CharField(choices=[('petrol', 'Gasolina'), ('diesel', 'Diesel'), ('hybrid', 'Hibrido'), ('plugin_hybrid', 'Hibrido enchufable'), ('electric', 'Electrico'), ('lpg', 'GLP')], default='petrol', max_length=20, verbose_name='combustible')),
                ('air_conditioning', models.BooleanField(default=True, verbose_name='aire acondicionado')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Menor primero. Fija como se ordenan en los selectores.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoria de vehiculo',
                'verbose_name_plural': 'categorias de vehiculo',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
