# Generated by Django 5.2.17 on 2026-09-09 20:44

import apps.fleet.models
import django.contrib.postgres.constraints
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # La ExclusionConstraint de los bloqueos necesita btree_gist.
        ('core', '0001_btree_gist'),
        ('fleet', '0001_initial'),
        ('offices', '0002_grupos_de_oficinas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('plate', models.CharField(error_messages={'unique': 'Ya hay un vehiculo con esa matricula.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La matricula son entre 4 y 10 letras o numeros, sin espacios ni guiones.', regex='^[A-Z0-9]{4,10}$')], verbose_name='matricula')),
                ('brand', models.CharField(max_length=60, verbose_name='marca')),
                ('model', models.CharField(max_length=80, verbose_name='modelo')),
                ('version', models.CharField(blank=True, max_length=80, verbose_name='version')),
                ('vin', models.CharField(blank=True, help_text='Numero de bastidor (VIN). 17 caracteres.', max_length=17, verbose_name='bastidor')),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Ultima lectura conocida. La actualiza el check-out.', verbose_name='kilometros')),
                ('fuel', models.CharField(choices=[('petrol', 'Gasolina'), ('diesel', 'Diesel'), ('hybrid', 'Hibrido'), ('plugin_hybrid', 'Hibrido enchufable'), ('electric', 'Electrico'), ('lpg', 'GLP')], max_length=20, verbose_name='combustible')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatico')], max_length=20, verbose_name='cambio')),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name='plazas')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='color')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='primera matriculacion')),
                ('itv_expiry', models.DateField(blank=True, help_text='Con la ITV caducada el coche no sale del parking.', null=True, verbose_name='caducidad de la ITV')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='caducidad del seguro')),
                ('insurance_company', models.CharField(blank=True, max_length=80, verbose_name='aseguradora')),
                ('insurance_policy', models.CharField(blank=True, max_length=60, verbose_name='numero de poliza')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('rented', 'Alquilado'), ('workshop', 'Taller'), ('cleaning', 'Limpieza'), ('blocked', 'Bloqueado'), ('retired', 'Baja')], db_index=True, default='available', max_length=20, verbose_name='estado')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.vehiclecategory', verbose_name='categoria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('current_office', models.ForeignKey(help_text='Donde esta aparcado ahora. Cambia con los traslados.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='offices.office', verbose_name='oficina actual')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('start_at', models.DateTimeField(verbose_name='desde')),
                ('end_at', models.DateTimeField(verbose_name='hasta')),
                ('reason', models.CharField(choices=[('workshop', 'Taller'), ('cleaning', 'Limpieza'), ('long_term', 'Larga duracion'), ('transfer', 'Traslado'), ('other', 'Otros')], default='workshop', max_length=20, verbose_name='motivo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'bloqueo de vehiculo',
                'verbose_name_plural': 'bloqueos de vehiculo',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['current_office', 'status'], name='fleet_vehicle_office_status'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['category', 'status'], name='fleet_vehicle_cat_status'),
        ),
        migrations.AddIndex(
            model_name='vehicleblock',
            index=models.Index(fields=['vehicle', 'start_at'], name='fleet_block_vehicle_start'),
        ),
        migrations.AddConstraint(
            model_name='vehicleblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='fleet_block_fin_posterior_al_inicio'),
        ),
        migrations.AddConstraint(
            model_name='vehicleblock',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(apps.fleet.models.TsTzRange('start_at', 'end_at', models.Value('[)')), '&&'), ('vehicle', '=')], name='fleet_block_sin_solapes', violation_error_message='Ese vehiculo ya tiene un bloqueo que se solapa con esas fechas.'),
        ),
    ]
