# Generated by Django 5.2.17 on 2026-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehiculos_y_bloqueos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tank_liters',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Capacidad del deposito. Con ella se calcula el combustible que falta al devolver. En blanco se usa el valor por defecto.', null=True, verbose_name='deposito (litros)'),
        ),
    ]
