# Generated by Django 5.2.17 on 2026-09-21 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_cargos_de_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('kind', models.CharField(choices=[('service', 'Revisión'), ('oil', 'Aceite y filtros'), ('itv', 'ITV'), ('tyres', 'Neumáticos'), ('brakes', 'Frenos'), ('breakdown', 'Avería'), ('bodywork', 'Chapa y pintura'), ('other', 'Otros')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_workshop', 'En taller'), ('done', 'Hecho'), ('cancelled', 'Anulado')], default='scheduled', max_length=20, verbose_name='estado')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('workshop', models.CharField(blank=True, max_length=120, verbose_name='taller')),
                ('scheduled_for', models.DateField(blank=True, null=True, verbose_name='fecha prevista')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='entrada en taller')),
                ('expected_end_at', models.DateTimeField(blank=True, null=True, verbose_name='salida prevista')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='salida real')),
                ('immobilizes', models.BooleanField(default=True, help_text='Mientras este en taller no se puede alquilar: se bloquea en el calendario.', verbose_name='inmoviliza el coche')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometros')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='coste')),
                ('supplier_invoice', models.CharField(blank=True, max_length=60, verbose_name='factura del taller')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='proximo vencimiento')),
                ('next_due_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='proximo a los km')),
                ('block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to='fleet.vehicleblock', verbose_name='bloqueo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'mantenimiento',
                'verbose_name_plural': 'mantenimientos',
                'ordering': ['-scheduled_for', '-created_at'],
                'default_permissions': ('view', 'add', 'change'),
                'indexes': [models.Index(fields=['vehicle', 'kind', 'status'], name='fleet_mant_coche_tipo')],
            },
        ),
    ]
