# Generated by Django 5.2.17 on 2026-09-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0008_cargos_de_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('kind', models.CharField(choices=[('confirmation', 'Confirmación de reserva'), ('reminder', 'Recordatorio e instrucciones de recogida'), ('contract', 'Contrato'), ('return', 'Devolución'), ('invoice', 'Factura'), ('payment_link', 'Enlace de pago'), ('payment_received', 'Pago recibido')], max_length=30, verbose_name='tipo')),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviado'), ('failed', 'Error'), ('skipped', 'No enviado')], default='queued', max_length=20, verbose_name='estado')),
                ('to_email', models.EmailField(blank=True, max_length=254, verbose_name='para')),
                ('language', models.CharField(default='es', max_length=5, verbose_name='idioma')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='asunto')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('provider_id', models.CharField(blank=True, max_length=120, verbose_name='id en el proveedor')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado el')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'correo enviado',
                'verbose_name_plural': 'correos enviados',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['reservation', 'kind'], name='notif_reserva_tipo')],
            },
        ),
    ]
